asyn:
  min_received_num: 13
  min_received_rate: -1.0
  timeout: 0
  use: true
attack:
  alpha_TV: 0.001
  alpha_prop_loss: 0
  attack_method: ''
  attacker_id: -1
  classifier_PIA: randomforest
  info_diff_type: l2
  inject_round: 0
  max_ite: 400
  reconstruct_lr: 0.01
  reconstruct_optim: Adam
  target_label_ind: -1
backend: torch
cfg_file: ''
criterion:
  type: MSELoss
data:
  args: []
  batch_size: 64
  cSBM_phi:
  - 0.5
  - 0.5
  - 0.5
  consistent_label_distribution: false
  drop_last: false
  graphsaint:
    num_steps: 30
    walk_length: 2
  loader: ''
  num_workers: 0
  pre_transform: []
  quadratic:
    dim: 1
    max_curv: 12.5
    min_curv: 0.02
  root: /Users/winston/CodingSpace/CIKM2022AnalytiCupCompetition/FormalData/
  server_holds_all: false
  shuffle: true
  sizes:
  - 10
  - 5
  splits:
  - 0.8
  - 0.1
  - 0.1
  splitter: ''
  splitter_args: []
  subsample: 1.0
  target_transform: []
  transform: []
  type: cikmcup
device: 0
distribute:
  use: false
early_stop:
  delta: 0.0
  improve_indicator_mode: mean
  patience: 20
  the_smaller_the_better: false
eval:
  base: 0.004389
  best_res_update_round_wise_key: val_loss
  count_flops: true
  freq: 5
  metrics:
  - imp_ratio
  monitoring: []
  report:
  - weighted_avg
  - avg
  - fairness
  - raw
  save_data: false
  split:
  - test
  - val
expname: FedAvg_gin_on_cikmcup_lr0.1_lstep15_hdsz128_drpt0.3_
expname_tag: ''
federate:
  client_num: 14
  data_weighted_aggr: false
  ignore_weight: false
  join_in_info: []
  make_global_eval: false
  method: FedAvg
  mode: standalone
  online_aggr: false
  restore_from: ''
  sample_client_num: 13
  sample_client_rate: -1.0
  sampler: uniform
  save_to: ''
  share_local_model: false
  total_round_num: 100
  unseen_clients_rate: 0.0
  use_diff: false
  use_ss: false
fedopt:
  use: false
fedprox:
  mu: 0.05
  use: true
fedsageplus:
  a: 1.0
  b: 1.0
  c: 1.0
  fedgen_epoch: 200
  gen_hidden: 128
  hide_portion: 0.5
  loc_epoch: 1
  num_pred: 5
finetune:
  batch_or_epoch: epoch
  before_eval: false
  freeze_param: ''
  local_update_steps: 1
  optimizer:
    lr: 0.1
    type: SGD
flitplus:
  factor_ema: 0.8
  lambdavat: 0.5
  tmpFed: 0.5
  weightReg: 1.0
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: false
grad:
  grad_clip: 1.0
hpo:
  fedex:
    cutoff: 0.0
    diff: false
    eta0: -1.0
    flatten_ss: true
    gamma: 0.0
    num_arms: 16
    sched: auto
    ss: ''
    use: false
  init_cand_num: 16
  larger_better: false
  log_scale: false
  metric: client_summarized_weighted_avg.val_loss
  num_workers: 0
  pbt:
    max_stage: 5
    perf_threshold: 0.1
  plot_interval: 1
  scheduler: rs
  sha:
    budgets: []
    elim_rate: 3
    elim_round_num: 3
  ss: ''
  table:
    eps: 0.1
    idx: 0
    num: 27
    ss: ''
  working_folder: hpo
model:
  dropout: 0.3
  embed_size: 8
  graph_pooling: mean
  hidden: 128
  in_channels: 0
  layer: 2
  model_num_per_trainer: 1
  num_item: 0
  num_user: 0
  out_channels: 12
  task: graphRegression
  type: gin
  use_bias: true
nbafl:
  use: false
outdir: exp/FedAvg_gin_on_cikmcup_lr0.1_lstep15_hdsz128_drpt0.3_
personalization:
  K: 5
  beta: 1.0
  local_param:
  - encoder_atom
  - encoder
  - clf
  - norms
  local_update_steps: 15
  lr: 0.1
  regular_weight: 0.1
  share_non_trainable_para: false
print_decimal_digits: 6
regularizer:
  mu: 0.05
  type: proximal_regularizer
seed: 0
sgdmf:
  use: false
train:
  batch_or_epoch: epoch
  local_update_steps: 15
  optimizer:
    lr: 0.05
    type: SGD
    weight_decay: 0.0005
trainer:
  type: graphminibatch_trainer
use_gpu: true
verbose: 1
vertical:
  use: false
wandb:
  use: false

